question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home "
             "to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Earth is flat.", "answer": "False"},
    {"text": "The capital of France is Paris.", "answer": "True"},
    {"text": "The chemical symbol for gold is Au.", "answer": "True"},
    {"text": "There are 50 states in the United States.", "answer": "True"},
    {"text": "The Great Wall of China is visible from the Moon.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Albert Einstein developed the theory of relativity.", "answer": "True"},
    {"text": "Light travels faster than sound.", "answer": "True"},
    {"text": "The Pacific Ocean is the largest ocean on Earth.", "answer": "True"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "Humans have three bones in each ear.", "answer": "True"},
    {"text": "The Great Wall of China was built in a single year.", "answer": "False"},
    {"text": "The speed of light is approximately 300,000 kilometers per second.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "The atomic number of carbon is 6.", "answer": "True"},
    {"text": "There are 206 bones in the adult human body.", "answer": "True"},
    {"text": "Water boils at 90 degrees Celsius.", "answer": "False"},
    {"text": "The Sahara is the largest desert in the world.", "answer": "True"},
    {"text": "Pluto is classified as a dwarf planet.", "answer": "True"},
    {"text": "The Mona Lisa was painted by Vincent van Gogh.", "answer": "False"},
    {"text": "Spiders are insects.", "answer": "False"},
    {"text": "There are seven continents on Earth.", "answer": "True"},
    {"text": "The capital city of Australia is Sydney.", "answer": "False"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The largest organ in the human body is the liver.", "answer": "False"},
    {"text": "A leap year has 366 days.", "answer": "True"},
    {"text": "Elephants are the largest land animals.", "answer": "True"},
    {"text": "Mercury is the smallest planet in the Solar System.", "answer": "True"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "False"},
    {"text": "Jupiter has the most moons of any planet in the Solar System.", "answer": "True"},
    {"text": "The human heart has four chambers.", "answer": "True"},
    {"text": "Dolphins are a type of fish.", "answer": "False"},
    {"text": "The chemical symbol for silver is Ag.", "answer": "True"},
    {"text": "The capital of Japan is Beijing.", "answer": "False"},
    {"text": "The Eiffel Tower is located in Berlin.", "answer": "False"},
    {"text": "The boiling point of water is 100 degrees Celsius.", "answer": "True"},
    {"text": "A triangle has three sides.", "answer": "True"},
    {"text": "The moon is a planet.", "answer": "False"},
    {"text": "Photosynthesis is the process by which plants make their own food.", "answer": "True"},
    {"text": "The chemical formula for water is H2O.", "answer": "True"},
    {"text": "Penguins are found only in the Arctic.", "answer": "False"},
    {"text": "The longest bone in the human body is the femur.", "answer": "True"},
    {"text": "The Great Pyramid of Giza is one of the Seven Wonders of the Ancient World.", "answer": "True"},
    {"text": "Birds are warm-blooded animals.", "answer": "True"},
    {"text": "The capital of Egypt is Cairo.", "answer": "True"},
    {"text": "The human brain is divided into four lobes.", "answer": "True"},
    {"text": "The currency of Japan is the yen.", "answer": "True"},
    {"text": "Mars is known as the Red Planet.", "answer": "True"},
    {"text": "The Sun is a star.", "answer": "True"},
    {"text": "The tallest building in the world is located in New York City.", "answer": "False"},
    {"text": "Venus is the second planet from the Sun.", "answer": "True"},
    {"text": "The currency of the United Kingdom is the dollar.", "answer": "False"},
    {"text": "The longest river in the world is the Nile.", "answer": "True"},
    {"text": "There are eight planets in the Solar System.", "answer": "True"},
    {"text": "The smallest bone in the human body is located in the ear.", "answer": "True"},
    {"text": "The capital of Italy is Rome.", "answer": "True"},
    {"text": "Saturn is known for its prominent ring system.", "answer": "True"},
    {"text": "The capital of Spain is Barcelona.", "answer": "False"},
    {"text": "Mount Kilimanjaro is located in Kenya.", "answer": "False"},
    {"text": "The human body is made up of approximately 60% water.", "answer": "True"},
    {"text": "Bees are capable of recognizing human faces.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "The human nose can detect over 1 trillion different scents.", "answer": "True"},
    {"text": "The largest planet in our solar system is Neptune.", "answer": "False"},
    {"text": "The Pacific Ocean is smaller than the Atlantic Ocean.", "answer": "False"},
    {"text": "The capital of Canada is Toronto.", "answer": "False"},
    {"text": "Sharks have been around longer than trees.", "answer": "True"},
    {"text": "The capital of South Korea is Seoul.", "answer": "True"},
    {"text": "The human eye can distinguish approximately 10 million different colors.", "answer": "True"},
    {"text": "The first human-made object to reach space was launched by the United States.", "answer": "False"},
    {"text": "Venus is hotter than Mercury despite being further from the Sun.", "answer": "True"},
    {"text": "The longest reigning British monarch was Queen Elizabeth I.", "answer": "False"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "The largest volcano in the solar system is on Earth.", "answer": "False"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "The primary ingredient in traditional Japanese miso soup is chicken.", "answer": "False"},
    {"text": "The capital of Brazil is Rio de Janeiro.", "answer": "False"},
    {"text": "Diamonds are the hardest natural substance on Earth.", "answer": "True"},
    {"text": "The first Olympic Games were held in Athens, Greece.", "answer": "False"},
    {"text": "There are more stars in the universe than grains of sand on all the world's beaches.", "answer": "True"},
    {"text": "The human skeleton renews itself completely every 10 years.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The capital of Argentina is Buenos Aires.", "answer": "True"},
    {"text": "The longest mountain range is the Andes.", "answer": "False"},
    {"text": "There are more cells of bacteria in your body than there are human cells.", "answer": "True"},
    {"text": "Peanuts are a type of nut.", "answer": "False"},
    {"text": "The capital of Turkey is Istanbul.", "answer": "False"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "The Great Wall of China is over 13,000 miles long.", "answer": "True"},
    {"text": "The capital of the United States is New York City.", "answer": "False"},
    {"text": "The capital of India is New Delhi.", "answer": "True"},
    {"text": "Jellyfish have a brain.", "answer": "False"},
    {"text": "The capital of Mexico is Mexico City.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The capital of Russia is Moscow.", "answer": "True"},
    {"text": "The human body has five senses.", "answer": "True"},
    {"text": "The tallest animal in the world is the elephant.", "answer": "False"},
    {"text": "The Mona Lisa is displayed in the Louvre Museum.", "answer": "True"},
    {"text": "Venus is the brightest planet in the night sky.", "answer": "True"},
    {"text": "The Sahara Desert is located in South America.", "answer": "False"},
    {"text": "Australia is both a country and a continent.", "answer": "True"},
    {"text": "The chemical symbol for sodium is Na.", "answer": "True"},
    {"text": "The tallest waterfall in the world is Niagara Falls.", "answer": "False"},
    {"text": "The first man to walk on the moon was Neil Armstrong.", "answer": "True"},
    {"text": "The capital of Germany is Berlin.", "answer": "True"},
    {"text": "A heptagon has eight sides.", "answer": "False"},
]
